config/routes.rb
Chatprivatepub2::Application.routes.draw do
  devise_for :users

   root :to => 'messages#index'
    match 'display_online_user', to: 'messages#onlineuser', via: [:get]

  resources :messages do 
    member do
      get 'chat'
 
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
    attr_accessible :user_id, :content, :receiver_id, :created_at
   
   belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :updated_at
  # attr_accessible :title, :body
  has_many :messages

  def online?
  updated_at > 10.seconds.ago
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  after_filter :user_activity

private

def user_activity
  current_user.try :touch
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
    @messages = Message.all
  end

  def create
  	user = User.find(params[:message][:receiver_id])
    @user = current_user
    @user1 = user
    @message = Message.create!(params[:message])  
    @channel = "/messages/private/#{user[:id]}/#{current_user[:id]}"
    @channel1 = "/messages/private/#{current_user[:id]}/#{user[:id]}"
    #@channel1 = "/messages/private/#{current_user[:id]}"
    
    #PrivatePub.publish_to("/messages/private/#{user[:id]}", message: @message)
    #PrivatePub.publish_to("/messages/private/#{current_user[:id]}", message: @message)

  end
  def chat
  	 
  	
    user = User.find(params[:id])
    @user = user
    
    @messages = Message.where(("user_id = '#{current_user[:id]}' AND receiver_id = '#{user[:id]}') OR (receiver_id = '#{current_user[:id]}' AND user_id = '#{user[:id]}'"))
    
    #@message = Message.new(:receiver_id=@user.id)
    #@message = Message.create!(params[:message])
    #@channel = "/messages/private/#{user[:id]}"
    
  end

  def onlineuser
    render :layout => false
  end  


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatprivatepub2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


<%= yield %>

<br />
<br />

<% if user_signed_in? %>
<%= "You're logged in as " %>
<%= current_user.email %>
<%= link_to('Logout', destroy_user_session_path, :method=>'delete')  %>
<% end %>
</body>
</html>

app/views/messages/_message.html.erb
  <%= message.user.email if message.user %>
   			
  <%= ":" %>
  <%= message.content %>
</br >

app/views/messages/_onlineuser.html.erb
<% @users = User.all %>
<% @users.each do |user| %>
<% if user != current_user and user.online? %>
  <%= link_to(user.email, chat_message_path(user.id)) %>
  <%#= subscribe_to "/messages/private/#{user[:email]}" %>
<% end %>
<% end %>

app/views/messages/chat.html.erb
<h1>Chat</h1>

<ul id="chat">
  <%# @messages= Message.where (user_id = current_user.id) %>
  <%= render @messages %>
</ul>
<%# @reciever_id = @user.id %>
<%= form_for Message.new, remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.hidden_field :user_id, :value => current_user.id %> 
  <%= f.hidden_field :receiver_id, :value => @user.id %> 
  <%= f.submit "Send" %>
<% end %>


<%= subscribe_to "/messages/private/#{current_user[:id]}/#{@user[:id]}" %>

app/views/messages/create.js.erb
<% publish_to @channel do %>
	$("#chat").append("<%= j render(@message) %>");
	<% end %>
<% publish_to @channel1 do %>
	$("#chat").append("<%= j render(@message) %>");
	<% end %>
$("#new_message")[0].reset();

app/views/messages/index.html.erb
<% if user_signed_in? %>

 <h1>Chat</h1>
<!--< ul id="chat">
  <%= render @messages %>
</ul>

<%= form_for Message.new, remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/new" %>
 -->
<!--  <div id="checkonlinestatus">
<%# @users = User.all %>
<%# @users.each do |user| %>
<%# if user != current_user and user.online? %>
   <%#= link_to(user.email, chat_message_path(user.id)) %>
  <%#= subscribe_to "/messages/private/#{user[:email]}" %>
<%# end %>
<%# end %>
</div>  -->

 <div id="checkonlinestatus">
  <%#= render 'onlineuser', :layout => false %>
</div>

<%= current_user.email %> 
<%= link_to('Logout', destroy_user_session_path, :method=>'delete')  %>

 

 <% else %>

<h1> Sign in to continue </h1>

                <%= link_to('Sign up', new_user_registration_path)  %>
              
              
                <%= link_to('Login', new_user_session_path)  %>

  <% end %>  
  <!-- script -->
   <script>
   $(document).ready(function(){
   	var auto_refresh = setInterval(function(){
  	$('#checkonlinestatus').load("<%= display_online_user_path %>");},10000);
   });
   </script>

app/views/messages/onlineuser.html.erb
<% @users = User.all %>
<% @users.each do |user| %>
<% if user != current_user and user.online? %>
  <%= link_to(user.email, chat_message_path(user.id)) %>
  <%#= subscribe_to "/messages/private/#{user[:email]}" %>
<% end %>
<% end %>

app/views/messages/show.html.erb
<h1>Chat</h1>

<ul id="chat">
  <%= render @messages(current_user[:id]) %>
</ul>

<%= form_for Message.new(user), remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/private/#{current_user[:id]}" %>